# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97288d4aa44bf804620e60352b638b16fcdd0f24b60cd417ee36087eb4f1a4fa8c533ea1c199f6d2939040b186aac59532210a1677fe6a4885a5b479a0732a30

test:
  secret_key_base: a8b73b7590abf399a92f22098e3a744b754741704539bca1994dd4cb564988aaf7da4f6a8a65851b251a91253a71310aad6c07fe88cbb0db3513701b2fc16487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
